name: Cross-platform tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - powerpc-unknown-linux-gnu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update to the latest Rust
        run: rustup update stable
      - name: Install cross-compilation tools
        uses: taiki-e/setup-cross-toolchain-action@v1.28.3
        with:
          target: ${{ matrix.target }}
      # for each target in matrix.target, setup-cross-toolchain-action sets the
      # `CARGO_BUILD_TARGET` and possibly `CARGO_TARGET_.._RUNNER` env vars for this command:
      - run: cargo test --verbose -- --nocapture
